<<<<<<< HEAD
version: "3"
services:
  persons-service:
    build: ./
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: 3001
    ports:
      - "3001:3001"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
=======
version: "3"
services:
  users-service:
    build: ./
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: 3001
    ports:
      - "3001:3001"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
>>>>>>> 8b76df367b8f9a89ace3b9397c9c1ab0a28c74b2
